### ISSUE TITLE
Regex marks valid IP address as invalid

### ISSUE THREAD

**Issue by compyman** [emailage/Emailage_Python#10]
Hello - I tried to submit a query with an ip address like: `155.155.0.101` which looks fine to me 
it passes the regex check if you change it to `155.155.10.101` it will pass.

**Comment by compyman** [comment]
(I'm on the most up to date version of the client this time)

**Comment by gtraines-emailage** [comment]
Hi @compyman ,
Are you saying that you were able to submit a request to the API and the API returned an invalid IP validation, or the client threw an exception without sending the request?

**Comment by compyman** [comment]
hi @gtraines-emailage the client threw an error without sending the request based on this regex:     

```python
ipv4_re = r'^([3-9]\d?|2(?:5[0-5]|[0-4]?\d)?|1\d{0,2})((\.([3-9]\d?|2(?:5[0-5]|[0-4]?\d)?|1\d{0,2})){3})$'
```
in `validation.py::assert_ip`

it appears that the 0 in the third group is not being allowed (i.e. the ip address matches the regex with 10 or 1 after `155.155.`

**Comment by gtraines-emailage** [comment]
@compyman  -- Roger that, fix is coming today.

**Comment by gtraines-emailage** [comment]
@compyman Updated, the new version is 1.1.4 and is available through PyPI as well.
