### ISSUE TITLE
The 'requests' and 'six' libraries are required to be installed before emailage.

### ISSUE THREAD

**Issue by capnfabs** [emailage/Emailage_Python#12]
I'm having trouble installing emailage-official when it's specified as part of a requirements.txt file, and there's nothing already in the virtual environment.

This is because setup.py imports 'emailage', and `emailage/__init__.py` references `emailage.client`, which uses all the dependencies of the project.

Normally this isn't a problem - I can just install `requests` and `six` before installing emailage - but on some environments, for example, Heroku, you don't have this much control over the build process.

Could you please consider breaking this dependency such that `pip install emailage-official` just works?

Please let me know if you need any additional information.

**Comment by gtraines-emailage** [comment]
Hi @capnfabs ,

I see what you're saying, we'll take care of it and let you know when it's done.

**Comment by gtraines-emailage** [comment]
@capnfabs Apologies for the delayed notification, but this fix is in the PyPI repo as of last week.

**Comment by capnfabs** [comment]
Hi @gtraines-emailage - thanks for this! It's working perfectly.
