### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by aarondtaveras** [emailage/Emailage_Python#16]
I've had no luck getting the base pip install and imports working on my machine or any virtual machines.

On my machine, I'm thrown several errors saying that "emailage.client" is not a module, and that "emailage" isn't a package. This is the only package that throws me this error - emailage is installed in the proper directory, my Python path includes the folder which it is installed within, and all troubleshooting points to the notion that there isn't an odd system bug on my end.

I attempted to try and install emailage-official over Repl.it to see if it was an issue on my system, and got a more detailed error log. Here is the error given while trying to pip install emailage-official : 

```
Invalid requirement: 'from emailage.client import EmailageClient'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, inparseString
    raise exc
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, inparseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in_parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, inparseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in_parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, inparseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse errorat "'emailage'"
```

As you can see, the error is also arising in the `from emailage.client import EmailageClient` line. This is where the issue was thrown on my local machine in several environments - within VSCode, my native terminal, and now within Repl.it's environment. 

Is this project still functioning/alive?

**Comment by aarondtaveras** [comment]
Fixed what the issue was all along on my machine.

I had hastily named the file I was testing emailage in "emailage.py". Python inexperience shooting me in the foot. Sorry about that

**Comment by gtraines-emailage** [comment]
It's all good, thank you for the update!

**Comment by aarondtaveras** [comment]
@gtraines-emailage Sorry to bother again, but would you be able to point me in the right direction regarding failure to authenticate?

In the example where: 
`client = EmailageClient('api key','auth token')`

I am entering my supplied account_sid and auth token into the correct fields and I'm receiving an Authentication Error - either a mismatch or not found user/consumer. Any idea as to what could be causing this?

**Comment by gtraines-emailage** [comment]
Two questions 
1. Which environment are you attempting to authenticate against?
2. Along with the query, are you supplying a parameter "user_email" with the value as one of the email addresses associated with your account?

**Comment by aarondtaveras** [comment]
@gtraines-emailage 
I'm trying to authenticate against a production environment, but I did attempt Sandbox too to no avail.
I did not supply the additional "user_email" parameter in my query.

**Comment by gtraines-emailage** [comment]
@aarondtaveras Try adding the user_email as a keyword parameter; for example:

```
client.query('test@example.com', user_email='admin@yourcompany.com')
```

**Comment by aarondtaveras** [comment]
@gtraines-emailage 
`response = client.query('aarondtaveras@gmail.com',user_email='aaron@centraldiligencegroup.com')
`
Unfortunately I'm still getting the same issue.

**Comment by aarondtaveras** [comment]
I've cross referenced my SID and auth token with the admin who registered for emailage's service and also attempted to supply their e-mail instead of my own in the user_email field, however we have the same SID and auth token and swapping our e-mails didn't change things either.

**Comment by gtraines-emailage** [comment]
@aarondtaveras 
Do you have access to login to your your company's Portal account? 
https://app.emailage.com/

If so, please log in and verify that you're able to submit queries using the Query Explorer:
https://app.emailage.com/document/API-Query-Explorer

**Comment by aarondtaveras** [comment]
@gtraines-emailage  
I was successfully able to login and use the query explorer.

**Comment by gtraines-emailage** [comment]
@aarondtaveras  
Great, in the Request text box do you see your email address as the value of the query string parameter, something like "&user_email=graham.traines%40emailage.com"?

**Comment by aarondtaveras** [comment]
Yes, I do see it : 

`user_email=aaron%40centraldiligencegroup.com`

**Comment by gtraines-emailage** [comment]
@aarondtaveras Can you try again without providing the user_email parameter? If this doesn't work, I'll have to refer you to our support team since I don't have any access to view production queries or credentials.

**Comment by aarondtaveras** [comment]
@gtraines-emailage I tried again without the user_email parameter, but unfortunately I received the same result. Thanks for all of your help! 👍
