### ISSUE TITLE
Possibility to set timeout for requests

### ISSUE THREAD

**Issue by bluefish6** [emailage/Emailage_Python#22]
Hi,

When sending a query via your Client, there is no possibility to set a timeout for the request. Could you please merge the following pull request: https://github.com/emailage/Emailage_Python/pull/21 ?

Best regards

**Comment by gtraines-emailage** [comment]
We're testing now. Thanks!

**Comment by gtraines-emailage** [comment]
Done and pushed to PyPI
https://pypi.org/project/emailage-official/1.2.0/
