### ISSUE TITLE
Python 2.7 incompatibility in POST requests

### ISSUE THREAD

**Issue by bluefish6** [emailage/Emailage_Python#26]
version 1.2.0 in https://github.com/emailage/Emailage_Python/pull/24/commits/a66b74d39ed4fd5e32e0e283478e38d49959a1d8#diff-60bc6d0e1237e90fd352225f9b3b997dR253 introduced a way to send POST requests that causes incompatibility with python 2.7, which can be easily averted by using `encode('utf-8')` instead of `bytes()`:

change from:
```
payload = bytes(self._assemble_quoted_pairs(api_params), encoding='utf_8')
```
to:
```
payload = self._assemble_quoted_pairs(api_params).encode('utf_8')
```

Please change it so it will still work in Python 2. I know that Python 2 is already EOL, but the workaround is too easy to implement to break the compatibility.

**Comment by ruiyang-emailage** [comment]
@bluefish6 
Thank you for your suggestions, we're testing it now

**Comment by ruiyang-emailage** [comment]
@bluefish6 
Done and pushed to PyPI
https://pypi.org/project/emailage-official/1.2.2/
